### ISSUE TITLE
[Question] if this mod compatible with Host_Fixes, i will install, otherwise i won't

### ISSUE THREAD

**Issue by CoolLKKPS** [Askanen/NoMoreCheatCompany#1]
same as topic

**Comment by CoolLKKPS** [comment]
@Askanen

**Comment by CoolLKKPS** [comment]
seems not work, will do more test, will close this issue ticket until i gather more information

**Comment by Askanen** [comment]
My mod is compatible with all others mods but can conflict with other anticheat.
